// Code generated by sqlc. DO NOT EDIT.
// Manually updated to include columns added by migrations 0009 and 0011.
// versions:
//   sqlc v1.30.0
// source: games.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

// allGameCols is the full ordered column list for SELECT * on the games table.
// Columns are listed in creation order; ALTER TABLE columns appear at the end.
const allGameCols = `id, code, status, host_id, bank_id, current_question_idx, started_at, ended_at, created_at, updated_at, round_size, quiz_id, current_round_idx`

// scanGame scans a single game row into a Game struct.
// The column order must match allGameCols exactly.
func scanGame(row interface{ Scan(...any) error }, i *Game) error {
	return row.Scan(
		&i.ID,
		&i.Code,
		&i.Status,
		&i.HostID,
		&i.BankID,
		&i.CurrentQuestionIdx,
		&i.StartedAt,
		&i.EndedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RoundSize,
		&i.QuizID,
		&i.CurrentRoundIdx,
	)
}

const advanceGameQuestion = `-- name: AdvanceGameQuestion :one
UPDATE games
SET current_question_idx = current_question_idx + 1
WHERE id = $1
  AND status = 'in_progress'
RETURNING ` + allGameCols

func (q *Queries) AdvanceGameQuestion(ctx context.Context, id uuid.UUID) (Game, error) {
	row := q.db.QueryRow(ctx, advanceGameQuestion, id)
	var i Game
	err := scanGame(row, &i)
	return i, err
}

const advanceGameRound = `-- name: AdvanceGameRound :one
UPDATE games
SET current_round_idx = $2,
    current_question_idx = 0
WHERE id = $1
  AND status = 'in_progress'
RETURNING ` + allGameCols

type AdvanceGameRoundParams struct {
	ID              uuid.UUID `json:"id"`
	CurrentRoundIdx int32     `json:"current_round_idx"`
}

func (q *Queries) AdvanceGameRound(ctx context.Context, arg AdvanceGameRoundParams) (Game, error) {
	row := q.db.QueryRow(ctx, advanceGameRound, arg.ID, arg.CurrentRoundIdx)
	var i Game
	err := scanGame(row, &i)
	return i, err
}

const cancelGame = `-- name: CancelGame :one
UPDATE games
SET status   = 'cancelled',
    ended_at = now()
WHERE id = $1
  AND status IN ('lobby', 'in_progress')
RETURNING ` + allGameCols

func (q *Queries) CancelGame(ctx context.Context, id uuid.UUID) (Game, error) {
	row := q.db.QueryRow(ctx, cancelGame, id)
	var i Game
	err := scanGame(row, &i)
	return i, err
}

const createGame = `-- name: CreateGame :one
INSERT INTO games (id, code, host_id, bank_id, round_size, quiz_id)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING ` + allGameCols

type CreateGameParams struct {
	ID        uuid.UUID   `json:"id"`
	Code      string      `json:"code"`
	HostID    uuid.UUID   `json:"host_id"`
	BankID    pgtype.UUID `json:"bank_id"`  // nullable: Valid=false for quiz-based games
	RoundSize int32       `json:"round_size"`
	QuizID    pgtype.UUID `json:"quiz_id"`  // nullable UUID
}

func (q *Queries) CreateGame(ctx context.Context, arg CreateGameParams) (Game, error) {
	row := q.db.QueryRow(ctx, createGame,
		arg.ID,
		arg.Code,
		arg.HostID,
		arg.BankID,
		arg.RoundSize,
		arg.QuizID,
	)
	var i Game
	err := scanGame(row, &i)
	return i, err
}

const endGame = `-- name: EndGame :one
UPDATE games
SET status   = 'completed',
    ended_at = now()
WHERE id = $1
  AND status = 'in_progress'
RETURNING ` + allGameCols

func (q *Queries) EndGame(ctx context.Context, id uuid.UUID) (Game, error) {
	row := q.db.QueryRow(ctx, endGame, id)
	var i Game
	err := scanGame(row, &i)
	return i, err
}

const getActiveGameByCode = `-- name: GetActiveGameByCode :one
SELECT ` + allGameCols + ` FROM games
WHERE code = $1
  AND status IN ('lobby', 'in_progress')`

func (q *Queries) GetActiveGameByCode(ctx context.Context, code string) (Game, error) {
	row := q.db.QueryRow(ctx, getActiveGameByCode, code)
	var i Game
	err := scanGame(row, &i)
	return i, err
}

const getGameByID = `-- name: GetGameByID :one
SELECT ` + allGameCols + ` FROM games WHERE id = $1`

func (q *Queries) GetGameByID(ctx context.Context, id uuid.UUID) (Game, error) {
	row := q.db.QueryRow(ctx, getGameByID, id)
	var i Game
	err := scanGame(row, &i)
	return i, err
}

const listGamesByHost = `-- name: ListGamesByHost :many
SELECT ` + allGameCols + ` FROM games
WHERE host_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3`

type ListGamesByHostParams struct {
	HostID uuid.UUID `json:"host_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

func (q *Queries) ListGamesByHost(ctx context.Context, arg ListGamesByHostParams) ([]Game, error) {
	rows, err := q.db.Query(ctx, listGamesByHost, arg.HostID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Game{}
	for rows.Next() {
		var i Game
		if err := scanGame(rows, &i); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countGamesByQuiz = `SELECT COUNT(*) FROM games WHERE quiz_id = $1`

func (q *Queries) CountGamesByQuiz(ctx context.Context, quizID uuid.UUID) (int64, error) {
	var n int64
	err := q.db.QueryRow(ctx, countGamesByQuiz, quizID).Scan(&n)
	return n, err
}

const startGame = `-- name: StartGame :one
UPDATE games
SET status     = 'in_progress',
    started_at = now()
WHERE id = $1
  AND status = 'lobby'
RETURNING ` + allGameCols

func (q *Queries) StartGame(ctx context.Context, id uuid.UUID) (Game, error) {
	row := q.db.QueryRow(ctx, startGame, id)
	var i Game
	err := scanGame(row, &i)
	return i, err
}
