// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: game_players.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const addPlayer = `-- name: AddPlayer :one
INSERT INTO game_players (id, game_id, display_name, session_token)
VALUES ($1, $2, $3, $4)
RETURNING id, game_id, display_name, score, session_token, joined_at, left_at
`

type AddPlayerParams struct {
	ID           uuid.UUID `json:"id"`
	GameID       uuid.UUID `json:"game_id"`
	DisplayName  string    `json:"display_name"`
	SessionToken string    `json:"session_token"`
}

func (q *Queries) AddPlayer(ctx context.Context, arg AddPlayerParams) (GamePlayer, error) {
	row := q.db.QueryRow(ctx, addPlayer,
		arg.ID,
		arg.GameID,
		arg.DisplayName,
		arg.SessionToken,
	)
	var i GamePlayer
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.DisplayName,
		&i.Score,
		&i.SessionToken,
		&i.JoinedAt,
		&i.LeftAt,
	)
	return i, err
}

const addScoreToPlayer = `-- name: AddScoreToPlayer :one
UPDATE game_players
SET score = score + $2
WHERE id = $1
RETURNING id, game_id, display_name, score, session_token, joined_at, left_at
`

type AddScoreToPlayerParams struct {
	ID    uuid.UUID `json:"id"`
	Score int32     `json:"score"`
}

func (q *Queries) AddScoreToPlayer(ctx context.Context, arg AddScoreToPlayerParams) (GamePlayer, error) {
	row := q.db.QueryRow(ctx, addScoreToPlayer, arg.ID, arg.Score)
	var i GamePlayer
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.DisplayName,
		&i.Score,
		&i.SessionToken,
		&i.JoinedAt,
		&i.LeftAt,
	)
	return i, err
}

const getPlayer = `-- name: GetPlayer :one
SELECT id, game_id, display_name, score, session_token, joined_at, left_at FROM game_players WHERE id = $1
`

func (q *Queries) GetPlayer(ctx context.Context, id uuid.UUID) (GamePlayer, error) {
	row := q.db.QueryRow(ctx, getPlayer, id)
	var i GamePlayer
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.DisplayName,
		&i.Score,
		&i.SessionToken,
		&i.JoinedAt,
		&i.LeftAt,
	)
	return i, err
}

const getPlayerBySessionToken = `-- name: GetPlayerBySessionToken :one
SELECT id, game_id, display_name, score, session_token, joined_at, left_at FROM game_players WHERE session_token = $1
`

func (q *Queries) GetPlayerBySessionToken(ctx context.Context, sessionToken string) (GamePlayer, error) {
	row := q.db.QueryRow(ctx, getPlayerBySessionToken, sessionToken)
	var i GamePlayer
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.DisplayName,
		&i.Score,
		&i.SessionToken,
		&i.JoinedAt,
		&i.LeftAt,
	)
	return i, err
}

const leaderboardForGame = `-- name: LeaderboardForGame :many
SELECT id, display_name, score
FROM game_players
WHERE game_id = $1
ORDER BY score DESC, joined_at ASC
`

type LeaderboardForGameRow struct {
	ID          uuid.UUID `json:"id"`
	DisplayName string    `json:"display_name"`
	Score       int32     `json:"score"`
}

func (q *Queries) LeaderboardForGame(ctx context.Context, gameID uuid.UUID) ([]LeaderboardForGameRow, error) {
	rows, err := q.db.Query(ctx, leaderboardForGame, gameID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LeaderboardForGameRow{}
	for rows.Next() {
		var i LeaderboardForGameRow
		if err := rows.Scan(&i.ID, &i.DisplayName, &i.Score); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActivePlayersInGame = `-- name: ListActivePlayersInGame :many
SELECT id, game_id, display_name, score, session_token, joined_at, left_at FROM game_players
WHERE game_id = $1
  AND left_at IS NULL
ORDER BY joined_at ASC
`

func (q *Queries) ListActivePlayersInGame(ctx context.Context, gameID uuid.UUID) ([]GamePlayer, error) {
	rows, err := q.db.Query(ctx, listActivePlayersInGame, gameID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GamePlayer{}
	for rows.Next() {
		var i GamePlayer
		if err := rows.Scan(
			&i.ID,
			&i.GameID,
			&i.DisplayName,
			&i.Score,
			&i.SessionToken,
			&i.JoinedAt,
			&i.LeftAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlayersInGame = `-- name: ListPlayersInGame :many
SELECT id, game_id, display_name, score, session_token, joined_at, left_at FROM game_players
WHERE game_id = $1
ORDER BY joined_at ASC
`

func (q *Queries) ListPlayersInGame(ctx context.Context, gameID uuid.UUID) ([]GamePlayer, error) {
	rows, err := q.db.Query(ctx, listPlayersInGame, gameID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GamePlayer{}
	for rows.Next() {
		var i GamePlayer
		if err := rows.Scan(
			&i.ID,
			&i.GameID,
			&i.DisplayName,
			&i.Score,
			&i.SessionToken,
			&i.JoinedAt,
			&i.LeftAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const clearPlayerLeft = `-- name: ClearPlayerLeft :exec
UPDATE game_players
SET left_at = NULL
WHERE id = $1
`

func (q *Queries) ClearPlayerLeft(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, clearPlayerLeft, id)
	return err
}

const markPlayerLeft = `-- name: MarkPlayerLeft :exec
UPDATE game_players
SET left_at = now()
WHERE id = $1
  AND left_at IS NULL
`

func (q *Queries) MarkPlayerLeft(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markPlayerLeft, id)
	return err
}

const setPlayerScore = `-- name: SetPlayerScore :one
UPDATE game_players
SET score = $2
WHERE id = $1
RETURNING id, game_id, display_name, score, session_token, joined_at, left_at
`

type SetPlayerScoreParams struct {
	ID    uuid.UUID `json:"id"`
	Score int32     `json:"score"`
}

func (q *Queries) SetPlayerScore(ctx context.Context, arg SetPlayerScoreParams) (GamePlayer, error) {
	row := q.db.QueryRow(ctx, setPlayerScore, arg.ID, arg.Score)
	var i GamePlayer
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.DisplayName,
		&i.Score,
		&i.SessionToken,
		&i.JoinedAt,
		&i.LeftAt,
	)
	return i, err
}
