// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"database/sql/driver"
	"fmt"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type GameStatus string

const (
	GameStatusLobby      GameStatus = "lobby"
	GameStatusInProgress GameStatus = "in_progress"
	GameStatusCompleted  GameStatus = "completed"
	GameStatusCancelled  GameStatus = "cancelled"
)

func (e *GameStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = GameStatus(s)
	case string:
		*e = GameStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for GameStatus: %T", src)
	}
	return nil
}

type NullGameStatus struct {
	GameStatus GameStatus `json:"game_status"`
	Valid      bool       `json:"valid"` // Valid is true if GameStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullGameStatus) Scan(value interface{}) error {
	if value == nil {
		ns.GameStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.GameStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullGameStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.GameStatus), nil
}

type QuestionType string

const (
	QuestionTypeText           QuestionType = "text"
	QuestionTypeMultipleChoice QuestionType = "multiple_choice"
)

func (e *QuestionType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = QuestionType(s)
	case string:
		*e = QuestionType(s)
	default:
		return fmt.Errorf("unsupported scan type for QuestionType: %T", src)
	}
	return nil
}

type NullQuestionType struct {
	QuestionType QuestionType `json:"question_type"`
	Valid        bool         `json:"valid"` // Valid is true if QuestionType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullQuestionType) Scan(value interface{}) error {
	if value == nil {
		ns.QuestionType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.QuestionType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullQuestionType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.QuestionType), nil
}

type Answer struct {
	ID            uuid.UUID          `json:"id"`
	GameID        uuid.UUID          `json:"game_id"`
	QuestionID    uuid.UUID          `json:"question_id"`
	PlayerID      uuid.UUID          `json:"player_id"`
	Answer        string             `json:"answer"`
	IsCorrect     bool               `json:"is_correct"`
	PointsAwarded int32              `json:"points_awarded"`
	SubmittedAt   pgtype.Timestamptz `json:"submitted_at"`
}

type Game struct {
	ID                 uuid.UUID          `json:"id"`
	Code               string             `json:"code"`
	Status             GameStatus         `json:"status"`
	HostID             uuid.UUID          `json:"host_id"`
	BankID             uuid.UUID          `json:"bank_id"`
	CurrentQuestionIdx int32              `json:"current_question_idx"`
	StartedAt          pgtype.Timestamptz `json:"started_at"`
	EndedAt            pgtype.Timestamptz `json:"ended_at"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	// RoundSize is added via migration 0009 — ALTER TABLE appends it last in SELECT *.
	RoundSize          int32              `json:"round_size"`
}

type GamePlayer struct {
	ID           uuid.UUID          `json:"id"`
	GameID       uuid.UUID          `json:"game_id"`
	DisplayName  string             `json:"display_name"`
	Score        int32              `json:"score"`
	SessionToken string             `json:"session_token"`
	JoinedAt     pgtype.Timestamptz `json:"joined_at"`
	LeftAt       pgtype.Timestamptz `json:"left_at"`
}

type Question struct {
	ID            uuid.UUID          `json:"id"`
	BankID        uuid.UUID          `json:"bank_id"`
	Type          QuestionType       `json:"type"`
	Prompt        string             `json:"prompt"`
	CorrectAnswer string             `json:"correct_answer"`
	Choices       []byte             `json:"choices"`
	Points        int32              `json:"points"`
	Position      int32              `json:"position"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type QuestionBank struct {
	ID          uuid.UUID          `json:"id"`
	OwnerID     uuid.UUID          `json:"owner_id"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Subscription struct {
	ID                   uuid.UUID          `json:"id"`
	UserID               uuid.UUID          `json:"user_id"`
	Plan                 string             `json:"plan"`
	Status               string             `json:"status"`
	CurrentPeriodEnd     pgtype.Timestamptz `json:"current_period_end"`
	StripeCustomerID     pgtype.Text        `json:"stripe_customer_id"`
	StripeSubscriptionID pgtype.Text        `json:"stripe_subscription_id"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID          uuid.UUID          `json:"id"`
	Auth0Sub    string             `json:"auth0_sub"`
	Email       pgtype.Text        `json:"email"`
	DisplayName pgtype.Text        `json:"display_name"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}
