// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddPlayer(ctx context.Context, arg AddPlayerParams) (GamePlayer, error)
	AddScoreToPlayer(ctx context.Context, arg AddScoreToPlayerParams) (GamePlayer, error)
	AdvanceGameQuestion(ctx context.Context, id uuid.UUID) (Game, error)
	CancelGame(ctx context.Context, id uuid.UUID) (Game, error)
	ClearPlayerLeft(ctx context.Context, id uuid.UUID) error
	CountQuestionsInBank(ctx context.Context, bankID uuid.UUID) (int32, error)
	// CreateDefaultBank inserts the owner's default bank. The partial unique index
	// question_banks_one_default_per_owner guarantees at most one per owner, so a
	// concurrent insert raises a unique violation rather than creating a duplicate.
	CreateDefaultBank(ctx context.Context, arg CreateDefaultBankParams) (QuestionBank, error)
	CreateGame(ctx context.Context, arg CreateGameParams) (Game, error)
	CreateQuestion(ctx context.Context, arg CreateQuestionParams) (Question, error)
	CreateQuestionBank(ctx context.Context, arg CreateQuestionBankParams) (QuestionBank, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteQuestion(ctx context.Context, id uuid.UUID) error
	DeleteQuestionBank(ctx context.Context, id uuid.UUID) error
	EndGame(ctx context.Context, id uuid.UUID) (Game, error)
	GetActiveGameByCode(ctx context.Context, code string) (Game, error)
	GetAnswer(ctx context.Context, arg GetAnswerParams) (Answer, error)
	// GetDefaultBank returns the owner's implicit "default" bank, if one exists.
	// Returns no rows when the user has not created a question inline yet.
	GetDefaultBank(ctx context.Context, ownerID uuid.UUID) (QuestionBank, error)
	GetGameByID(ctx context.Context, id uuid.UUID) (Game, error)
	GetPlayer(ctx context.Context, id uuid.UUID) (GamePlayer, error)
	GetPlayerBySessionToken(ctx context.Context, sessionToken string) (GamePlayer, error)
	GetQuestion(ctx context.Context, id uuid.UUID) (Question, error)
	GetQuestionBank(ctx context.Context, id uuid.UUID) (QuestionBank, error)
	GetSubscriptionByStripeSubID(ctx context.Context, stripeSubscriptionID pgtype.Text) (Subscription, error)
	GetSubscriptionByUser(ctx context.Context, userID uuid.UUID) (Subscription, error)
	GetUserByAuth0Sub(ctx context.Context, auth0Sub string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	LeaderboardForGame(ctx context.Context, gameID uuid.UUID) ([]LeaderboardForGameRow, error)
	ListActivePlayersInGame(ctx context.Context, gameID uuid.UUID) ([]GamePlayer, error)
	ListAnswersForGame(ctx context.Context, gameID uuid.UUID) ([]Answer, error)
	ListAnswersForPlayer(ctx context.Context, playerID uuid.UUID) ([]Answer, error)
	ListAnswersForQuestion(ctx context.Context, arg ListAnswersForQuestionParams) ([]Answer, error)
	ListGamesByHost(ctx context.Context, arg ListGamesByHostParams) ([]Game, error)
	ListPlayersInGame(ctx context.Context, gameID uuid.UUID) ([]GamePlayer, error)
	ListQuestionBanksByOwner(ctx context.Context, ownerID uuid.UUID) ([]QuestionBank, error)
	ListQuestionsByBank(ctx context.Context, bankID uuid.UUID) ([]Question, error)
	MarkPlayerLeft(ctx context.Context, id uuid.UUID) error
	RecordAnswer(ctx context.Context, arg RecordAnswerParams) (Answer, error)
	ReorderQuestion(ctx context.Context, arg ReorderQuestionParams) (Question, error)
	SetPlayerScore(ctx context.Context, arg SetPlayerScoreParams) (GamePlayer, error)
	StartGame(ctx context.Context, id uuid.UUID) (Game, error)
	UpdateQuestion(ctx context.Context, arg UpdateQuestionParams) (Question, error)
	UpdateQuestionBank(ctx context.Context, arg UpdateQuestionBankParams) (QuestionBank, error)
	UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error)
	// Subscriptions queries are defined but unused until billing ships. Keeping them
	// here so the EntitlementChecker implementation has a ready-to-go data access
	// layer when Stripe is wired up.
	UpsertSubscription(ctx context.Context, arg UpsertSubscriptionParams) (Subscription, error)
	UpsertUserByAuth0Sub(ctx context.Context, arg UpsertUserByAuth0SubParams) (User, error)
}

var _ Querier = (*Queries)(nil)
